version: "3"
services:
  app:
    build: .
    restart: always
    tty: true
    env_file:
      - .env
    ports:
      - "${DOCKER_WEB_PORT:-8080}:8080"
    volumes:
      - .:/go/src/app
      - go-data:/go
volumes:
  go-data:
